name: Android CI - build custom APK

on:
  push:
    branches: [ "custom-apk" ]

permissions:
  contents: read

jobs:
  build:
    name: Build custom APK from project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout StreetComplete
      uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
#        cache: gradle

#    - name: Adding my keystore file content from secret
#      run: |
#        cd keystores/ && echo "${{ secrets.MY_KEYSTORE_FILE_BASE64 }}" > ./my.keystore.encoded.txt && openssl base64 -d -in ./my.keystore.encoded.txt -out ./my.keystore && ls -al

    - name: Get current date with timezone into env variable
      run: |
        echo "DATE_LAST_BUILD=$(TZ=':Europe/Bucharest' date +'%Y%m%d')" >> "$GITHUB_ENV"    && \
        echo "DATETIME_LAST_BUILD=$(TZ=':Europe/Bucharest' date +'%F\ %H:%M\ %Z')" >> "$GITHUB_ENV"

    - name: Applying custom patch
      env:
        APP_VERSION: "53.1"           #
        APP_VERCODE: 5302             #
      run: |
        chmod +x ./.patch/prebuild*.sh   &&  \
        ./.patch/prebuild-only-rename.sh "$APP_VERSION" "$APP_VERCODE"

    # https://github.com/marketplace/actions/gradle-build-action
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
      #with:
        #gradle-version: 6.5    # 7.5 used as defined in gradle-wrapper.properties
        #option: '--no-build-cache'

#    - name: Cleanup previous build directory
#      run: ./gradlew clean

    - name: Build Android APK with Gradle
#      env:
#        TARGET_APP_NAME: "StreetComplete DjBpF"
#        APP_EDITION: "${{ env.DATETIME_LAST_BUILD }}"         # automatic
      run: ./gradlew assembleDebug

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/StreetComplete-debug-$(git log -n 1 --format='%h').apk

    - name: Archive APK (Upload artifact)
      uses: actions/upload-artifact@v3
      with:
        name: custom-apk-debug-${{ github.run_number }}      # .zip will be added
        path: app/build/outputs/apk/*/*.apk
        retention-days: 30
